### ISSUE TITLE
Cannot get in ssh after all the public private key pair on aarch64

### ISSUE THREAD

**Issue by codecrypt92** [hnpl/hpc-disk-image#1]
Hi, 
I have tried all the steps but I still cannot ssh inside the qemu container. 
The qemu image gets stuck at login password and no login combination works. This is a 22.04 image as mentioned in your readme. 
`#cloud-config
users:
  - name: ubuntu
    lock_passwd: false
    groups: sudo
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    shell: /bin/bash
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAB`

My qemu launch: 

`dd if=/dev/zero of=flash0.img bs=1M count=64
dd if=/usr/share/qemu-efi-aarch64/QEMU_EFI.fd of=flash0.img conv=notrunc
dd if=/dev/zero of=flash1.img bs=1M count=64
qemu-system-aarch64 -m 16384 -smp 8 -cpu host -M virt -M gic-version=3 --enable-kvm  \
    -nographic -pflash flash0.img -pflash flash1.img \
    -drive if=none,file=arm64-hpc-2204.img,id=hd0 -device virtio-blk-device,drive=hd0 \
    -drive if=none,id=cloud,file=cloud.img -device virtio-blk-device,drive=cloud \
    -netdev user,id=user0 -device virtio-net-device,netdev=eth0 \
    -netdev user,id=eth0,hostfwd=tcp::5555-:22`

Which brings me to 2 questions:
- What is the default login password combination ? I tried ubuntu/ubuntu but nothing works. 
- ssh cannot login into the image. I have to manually kill qemu pids every time due to this. 
Due to which packer gets stuck looking for ssh.

Thanks in advance.

**Comment by hnpl** [comment]
Hi there,

> What is the default login password combination ? I tried ubuntu/ubuntu but nothing works.

The base disk image that is used for creating the ARM disk image is a cloud disk image, and if I remember correctly, the disk image is setup in a way that doesn't allow logging in using password. So, we'll have to rely on public/private keys-based authentication.

Please make sure that the keys are setup correctly. The `ssh-authorized-keys` field of the `cloud.txt` file should be the content of the public key that you generated in previous steps. Typically, if your public key is in `~/.ssh/id_rsa.pub`, then the content of the `ssh-authorized-keys` should be the same as the content of `~/.ssh/id_rsa.pub`.

> ssh cannot login into the image. I have to manually kill qemu pids every time due to this.
Due to which packer gets stuck looking for ssh.

To exit a qemu instance, you can use the following key combination: `ctrl+a` then `x`.
